'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PONG.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property beeep() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("beeep", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property BowFireArrow() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("BowFireArrow", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property missilegraph1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("missilegraph1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property missilegraph2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("missilegraph2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property peeeeeep() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("peeeeeep", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property plop() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("plop", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property PowerUp() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("PowerUp", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property PumpShotgun() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("PumpShotgun", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property raygun() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("raygun", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Untitled() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Untitled", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
